force-app/main/default/objects/Candidate_Submission__c/Candidate_Submission__c.object-meta.xml
<CustomObject>
    <label>Candidate Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidate Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Interview ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate_Submission__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Submission__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate Submission</label>
    <referenceTo>Candidate_Submission__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InterviewTriggerHandler.cls
public with sharing class InterviewTriggerHandler {

    public static void handle(System.TriggerOperation operationType, 
                              list<Interview__c> newList, 
                              list<Interview__c> oldList){
        switch on operationType{
	
	        WHEN AFTER_INSERT{
                Set<Id> submissionIds = getSubmissionIds(newList);
		        InterviewService.recalculateInterviewCount(submissionIds);
		    }
		    WHEN AFTER_DELETE{
                Set<Id> submissionIds = getSubmissionIds(oldList);
		        InterviewService.recalculateInterviewCount(submissionIds);
		    }
		    WHEN AFTER_UNDELETE{
                Set<Id> submissionIds = getSubmissionIds(newList);
		        InterviewService.recalculateInterviewCount(submissionIds);
		    }
	    }
    }

    private static set<Id> getSubmissionIds(list<Interview__c> interviews){
        
        Set<Id> ids = new Set<Id>();
        if(interviews == null || interviews.isEmpty()){
            return ids;
        }
        for(Interview__c i: interviews){
            if(i.Candidate_Submission__c != null){
                ids.add(i.Candidate_Submission__c);
            }   
        }
        return ids;
    }
}